[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"
padding = { x = 4, y = 4 }
dimensions = { columns = 120, lines = 25 }

[cursor]
unfocused_hollow = false

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[general]
live_config_reload = true
import = ["colors/oxocarbon.toml", "fonts/sarasa.toml"]
