[font]
size = 14

[font.normal]
family = "Sarasa Term J"
style = "SemiBold"

[font.bold]
family = "Sarasa Term J"
style = "Bold"

[font.bold_italic]
family = "Sarasa Term J"
style = "Bold Italic"

[font.italic]
family = "Sarasa Term J"
style = "Italic"
