#!/bin/sh

pgrep -x sxhkd > /dev/null                               || sxhkd &
pgrep -x picom > /dev/null                               || picom --config "$HOME"/.config/picom/bspicom.conf &
pgrep -x polkit-gnome-authentication-agent-1 > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pgrep -x polybar > /dev/null                             || polybar bspwm -r &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
# switch off weeaboo numbers
# bspc monitor ^1 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_radius         20 # 20
bspc config border_width          0  # 3
bspc config window_gap            0  # 10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config focus_follows_pointer true

# bspc config focused_border_color "#FFDEDE" 
# bspc config normal_border_color "#A3CBE7"
# bspc config active_border_color "#B4E3AD"
# bspc config presel_feedback_color "#E5A3A1"

bspc wm --adopt-orphans

feh --bg-fill --no-fehbg --randomize ~/Images/Wallpapers &
